#!/usr/bin/env bash
# This script configures domainxzones so that www points to my load-balancer IP

#printer ()
#{
#	printf "The subdomain %s is a " "$2"
#	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
#	printf " record and points to "
#	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
#	echo ""
#}

#if [ -z "$2" ]; then
#	for subdomains in "www" "lb-01" "web-01" "web-02"
#	do
#		printer "$1" "$subdomains"
#	done
#else
#	printer "$1" "$2"
#fi


if [ "$#" = 1 ]
then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${subdomains[@]}"
    do
	record_type=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        destination=$(dig $sub_domain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
	echo "The subdomain $sub_domain is a $record_type record and points to $destination"
    done
elif [ "$#" = 2 ]
then
    record_type=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    destination=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $destination"
fi
