#!/usr/bin/env bash
# This script transfers a file from our client to a server

# check that the number of parameters given is 4
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/;
#    exit 1
fi
# assign the parameters to the variables
# filePath = "$1"
# IPServer = "$2"
# username = "$3"
# SSHPrivateKey = "$4"

# scp must be used to transfer the file to the user home directory
# scp "$filePath"
#"username@IPServer: $SSHPrivateKey"

# Then check if the transfer was successful
# if [ $? -eq 0 ]; then
