#!/usr/bin/bash env

# this replaces a line with multiple lines with sed
# i.e the nginx server should be configured to redirect /redirect_me
# to another page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/duke_ibadan permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
