#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.html
sudo sed -i "19i rewrite ^/redirect_me https://twitter.com/duke_ibadan permanent;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

sudo service nginx restart
