#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.html
TEXT="location /redirect_me {\\n return 301 https://www.twitter.com/duke_ibadan;\\n}\\n"
sudo sed -i "421 $TEXT" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
CUSTOM="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
sudo service nginx restart
