#!/usr/bin/env bash
# this cdoubles my current number of webservers by configuring a new one

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/http {/a \ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
